### ISSUE TITLE
add license?

### ISSUE THREAD

**Issue by cobbzilla** [philios33/PHP-AES-File-Encryption#1]
I'd like to include this code in another project I'm working on -- my project is AGPL and I'm diligent about ensuring appropriate licenses on any other code included. Would you consider putting your code under a GPL-ish or Apache/MIT-ish license?

**Comment by philios33** [comment]
Thanks, I had been meaning to set one.  It is my belief that this type of software should really be free for everyone, especially since it is based on a completely free to use open source file format which I did not invent.  I will choose MIT since it seems to be the least restrictive license out there.
